# Type stub for ingescape library
# This provides autocomplete support in IDEs

"""
Ingescape Type Stubs
Provides type hints and autocomplete for the ingescape library
"""

from typing import Any, Callable, List, Optional, Union

# Constants for data types
INTEGER_T: int
DOUBLE_T: int
BOOL_T: int
STRING_T: int
IMPULSION_T: int
DATA_T: int

# Constants for events
PEER_ENTERED: int
PEER_EXITED: int
AGENT_ENTERED: int
AGENT_UPDATED_DEFINITION: int
AGENT_KNOWS_US: int
AGENT_EXITED: int
AGENT_UPDATED_MAPPING: int
AGENT_WON_ELECTION: int
AGENT_LOST_ELECTION: int

# Logging functions
def info(message: str) -> None: ...
def warn(message: str) -> None: ...
def error(message: str) -> None: ...
def debug(message: str) -> None: ...
def trace(message: str) -> None: ...

# Agent management
def agent_set_name(name: str) -> None: ...
def agent_name() -> str: ...
def start_with_device(device: str, port: int) -> None: ...
def start_with_ip(ip: str, port: int) -> None: ...
def stop() -> None: ...
def is_started() -> bool: ...

# Input/Output management
class input:
    @staticmethod
    def create(name: str, value_type: int, value: Any = None) -> None: ...
    
    @staticmethod
    def remove(name: str) -> None: ...
    
    @staticmethod
    def set_bool(name: str, value: bool) -> None: ...
    
    @staticmethod
    def set_int(name: str, value: int) -> None: ...
    
    @staticmethod
    def set_double(name: str, value: float) -> None: ...
    
    @staticmethod
    def set_string(name: str, value: str) -> None: ...
    
    @staticmethod
    def set_impulsion(name: str) -> None: ...
    
    @staticmethod
    def bool(name: str) -> bool: ...
    
    @staticmethod
    def int(name: str) -> int: ...
    
    @staticmethod
    def double(name: str) -> float: ...
    
    @staticmethod
    def string(name: str) -> str: ...

class output:
    @staticmethod
    def create(name: str, value_type: int, value: Any = None) -> None: ...
    
    @staticmethod
    def remove(name: str) -> None: ...
    
    @staticmethod
    def set_bool(name: str, value: bool) -> None: ...
    
    @staticmethod
    def set_int(name: str, value: int) -> None: ...
    
    @staticmethod
    def set_double(name: str, value: float) -> None: ...
    
    @staticmethod
    def set_string(name: str, value: str) -> None: ...
    
    @staticmethod
    def set_impulsion(name: str) -> None: ...

# Legacy functions (for backward compatibility)
def output_set_impulsion(name: str) -> None: ...
def input_set_bool(name: str, value: bool) -> None: ...
def input_set_int(name: str, value: int) -> None: ...
def input_set_double(name: str, value: float) -> None: ...
def input_set_string(name: str, value: str) -> None: ...
def output_set_bool(name: str, value: bool) -> None: ... 
def output_set_int(name: str, value: int) -> None: ...
def output_set_double(name: str, value: float) -> None: ... 
def output_set_string(name: str, value: str) -> None: ...
def output_create(name: str, value_type: int, value: Any = None) -> None: ...
def input_create(name: str, value_type: int, value: Any = None) -> None: ...
def log_set_console(enabled: bool) -> None: ...
def log_set_file(enabled: bool, filename: Optional[str] = None) -> None: ...
def log_set_stream(enabled: bool) -> None: ...
def set_command_line(args: str) -> None: ...

# Callback functions
def observe_input(name: str, callback: Callable[[str, Any, Any], None]) -> None: ...
def observe_output(name: str, callback: Callable[[str, Any, Any], None]) -> None: ...
def observe_agent_events(callback: Callable[[str, int, str], None], agent: str) -> None: ...
def observe_freeze(callback: Callable[[], None], agent: str) -> None: ...


# Service functions
def service_call(agent: str, service: str, *args: Any) -> None: ...
def service_init(name: str, callback: Callable) -> None: ...

# Mapping and networking
def mapping_load_str(mapping: str) -> None: ...
def mapping_load_file(path: str) -> None: ...

# Definition
def definition_set_description(description: str) -> None: ...
def definition_set_version(version: str) -> None: ...